services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=token_billing'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '54323:5432'
